### ISSUE TITLE
ER図作成するためのgemを追加

### ISSUE THREAD

**Issue by knao124** [kuboshizuma/FiNC_blog#1]
```
group :development do 
  gem 'rails-erd'
end
```

をGemfileに追加して
$ bundle install
$ bundle exec erd
でerd.pdfができあがります。

ER図（table構造を可視化したもの）がぱっとワンコマンドで作成できるいいgemなので、いれておいてください。どのプロジェクトでも使用しています。

**Comment by kuboshizuma** [comment]
$ bundle exec erd
ではうまくいかなかったのですが、
$rake erd
とやるとうまくいきました。
