### ISSUE TITLE
記事詳細でエラーが出る

### ISSUE THREAD

**Issue by knao124** [kuboshizuma/FiNC_blog#2]
![2015-04-20 13 38 20 2](https://cloud.githubusercontent.com/assets/4919012/7223763/8cc463fc-e762-11e4-954e-377e6a370e8e.png)

**Comment by kuboshizuma** [comment]
エラーの原因はmigrationファイルで作成されないカラムが存在することでした。
カラムを追加するときに、mysqlで直接作成したものがcloneしてきたアプリ内では反映されていませんでした。

migrationファイルの作成で対応しました。

**Comment by knao124** [comment]
@kuboshizuma おつ！pullrequestをマージするときに、close #2 もしくはclosed #2 、fixed #2、fix #2、とうつと、勝手に指定したissueをマージしてくれるから今度つかってみて！

**Comment by kuboshizuma** [comment]
次回以降やってみます！
