### ISSUE TITLE
サイドバーにTimelineを表示する。

### ISSUE THREAD

**Issue by knao124** [kuboshizuma/FiNC_blog#6]

**Comment by kuboshizuma** [comment]
### タイムライン作成手順
* [ ] timelineのロジックを作成->下記「タイムラインに表示される表示タイプ一覧」の各項を作成する
* [ ] timelineのロジックをtimelineのModelを作成し移行
* [ ] before_actionを使ってtimelimeModelからデータを呼びこむ
* [ ] Viewへの表示
* [ ] Viewのスタイリング

### タイムラインに表示される表示タイプ一覧
* [x] ①フォローされた
ー「」さんにフォローされました！
* [x] ②フォローした
ー「」さんをフォローしました！
* [x] ③記事を書いた
ーあなたが記事「」を書きました！
* [x] ④自分の書いた記事にコメントがついた
ーあなたの記事「」にコメントがつきました！
* [ ] ⑤自分の書いた記事にお気に入りがついた
ーあなたの記事「」にお気に入りがつきました！
* [ ] ⑥自分の書いたコメントにお気に入りがついた
ーあなたのコメント「」にお気に入りがつきました！
